[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "solana"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.10.34"
description = "solana blockchain validator"
api_host = "http://localhost:8899/"
ports = [8899]
data_directory_mount_point = "/blockjoy/miner/data"

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "getBlockHeight"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "address"
transport = "jrpc"
method = "getClusterNodes"
    
    [methods.response]
    code = 200
    field = "pubkey"

[[methods]]
name = "status"
transport = "jrpc"
method = "getHealth"

    [methods.response]
    code = 200
    field = "result"
