[package]
name = "babel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "babel"
path = "src/lib.rs"

[[bin]]
name = "babel"
path = "src/bin/babel.rs"

[[bin]]
name = "babelsup"
path = "src/bin/babelsup.rs"

[dependencies]
async-trait = "0.1.61"
babel_api = {version = "*", path = "../babel_api"}
crc = "3.0.0"
ctrlc = "3.2.4"
eyre = "0.6.8"
futures = "0.3.25"
gjson = "0.8"
lazy_static = "1.4.0"
reqwest = {version = "0.11.14", features = ["json", "rustls"], default-features = false}
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
sysinfo = "0.27.7"
thiserror = "1.0.31"
tokio = {version = "1.0", features = ["fs", "io-std", "io-util", "macros", "process", "rt-multi-thread"]}
tokio-stream = "0.1.11"
tonic = "0.8.3"
tracing = "0.1.37"
tracing-subscriber = {version = "0.3.16", features = ["env-filter", "fmt", "std"], default-features = false}

[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = {version = "0.4.0", features = ["tonic-conn"]}

[dev-dependencies]
assert_fs = "1"
httpmock = "0.6.7"
mockall = "0.11.3"
postcard = {version = "1.0.2", features = ["alloc"]}
tokio-stream = {version = "0.1.11", features = ["net"]}
tokio-util = {version = "0.7.4", features = ["io"]}
tower = "0.4.13"
walkdir = "2"
toml = "0.5.11"
