[package]
edition = "2021"
name = "babel"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "babel"
path = "src/lib.rs"

[[bin]]
name = "babel"
path = "src/main.rs"

[features]
vsock = ["dep:tokio-vsock"]

[dependencies]
async-io = "1.7.0"
eyre = "0.6.8"
futures = "0.3.21"
gjson = "0.8"
ctrlc = "3.2.3"
reqwest = {version = "0.11.11", features = ["json", "rustls"], default-features = false}
serde = {version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = {version = "1.0", features = ["fs", "io-std", "io-util", "macros", "process", "rt-multi-thread"]}
tokio-vsock = {version = "0.3.2", optional = true}
toml = "0.5.9"
tracing = "0.1.35"
tracing-subscriber = {version = "0.3.11", features = ["env-filter", "fmt", "std"], default-features = false}
async-trait = "0.1.58"

[dev-dependencies]
mockall = "0.11.3"
tokio-stream = "0.1.11"
tokio-util = {version = "0.7.4", features = ["io"]}
serial_test = "0.9.0"
httpmock = "0.6"
walkdir = "2"
