[package]
name = "babel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-io = "1.7.0"
eyre = "0.6.8"
futures = "0.3.21"
serde = "1.0.137"
serde_derive = "1.0.137"
serde_json = "1.0.81"
tracing = "0.1.35"
tracing-subscriber = "0.3.15"
tokio = { version = "1.0", features = ["fs", "io-std", "io-util", "macros", "process", "rt-multi-thread"] }
toml = "0.5.9"
zbus = { version = "3.1.0", features = ["tokio-vsock"], default-features = false}
reqwest = { version = "0.11.11", features = ["json", "rustls"], default-features = false }
tokio-vsock = "0.3.2"
