[package]
name = "babel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "babel"
path = "src/lib.rs"

[[bin]]
name = "babel"
path = "src/bin/babel.rs"

[[bin]]
name = "babelsup"
path = "src/bin/babelsup.rs"

[dependencies]
babel_api = {version = "*", path = "../babel_api"}
eyre = "0.6.8"
base64 = "0.21.0"
postcard = "1.0.2"
futures = "0.3.25"
gjson = "0.8"
ctrlc = "3.2.4"
lazy_static = "1.4.0"
reqwest = {version = "0.11.13", features = ["json", "rustls"], default-features = false}
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.91"
tokio = {version = "1.0", features = ["fs", "io-std", "io-util", "macros", "process", "rt-multi-thread"]}
tokio-stream = "0.1.11"
thiserror = "1.0.31"
toml = "0.5.10"
tonic = {version = "0.7.2", features = ["tls-roots"]}
tracing = "0.1.35"
tracing-subscriber = {version = "0.3.11", features = ["env-filter", "fmt", "std"], default-features = false}
async-trait = "0.1.61"
crc = "3.0.0"
prost = "0.10"
prost-types = "0.10"
sysinfo = "0.27.5"

[build-dependencies]
tonic-build = {version = "0.7.2", features = ["prost"]}

[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = {git = "https://github.com/blockjoy/tokio-vsock.git", features = ["tonic-conn"]}

[dev-dependencies]
assert_fs = "1.0.10"
mockall = "0.11.3"
tokio-stream = {version = "0.1.11", features = ["net"]}
tokio-util = {version = "0.7.4", features = ["io"]}
serial_test = "0.10.0"
httpmock = "0.6.7"
walkdir = "2"
tower = "0.4.13"
postcard = {version = "1.0.2",features= ["alloc"]}
