[package]
name = "babel"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "babel"
path = "src/lib.rs"

[[bin]]
name = "babel"
path = "src/bin/babel.rs"

[[bin]]
name = "babelsup"
path = "src/bin/babelsup.rs"

[dependencies]
babel_api = {version = "*", path = "../babel_api"}
eyre = "0.6.8"
futures = "0.3.21"
gjson = "0.8"
ctrlc = "3.2.3"
reqwest = {version = "0.11.11", features = ["json", "rustls"], default-features = false}
serde = {version = "1.0.137", features = ["derive"]}
serde_json = "1.0.81"
tokio = {version = "1.0", features = ["fs", "io-std", "io-util", "macros", "process", "rt-multi-thread"]}
thiserror = "1.0.31"
toml = "0.5.9"
tracing = "0.1.35"
tracing-subscriber = {version = "0.3.11", features = ["env-filter", "fmt", "std"], default-features = false}
async-trait = "0.1.58"

[target.'cfg(target_os = "linux")'.dependencies]
tokio-vsock = "0.3.2"

[dev-dependencies]
assert_fs = "1.0.7"
mockall = "0.11.3"
tokio-stream = "0.1.11"
tokio-util = {version = "0.7.4", features = ["io"]}
serial_test = "0.9.0"
httpmock = "0.6"
walkdir = "2"
