[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "kava"
node_type = "validator"
babel_version = "0.0.1"
node_version = "0.16.1" # recc mainnet
description = "kava blockchain validator"
api_host = "http://localhost:26656/"
# kava evm endopoint to connect to metamask: http://localhost:8545
ports = [26656, 8545]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "rest"
method = "blocks/latest"

    [methods.response]
    status = 200
    field = "block.height"
    format = "json"

[[methods]]
name = "address"
transport = "rest"
method = "kava/hard/v1beta1/accounts"

    [methods.response]
    status = 200
    field = "accounts.base_account.pub_key.value"
    format = "json"

[[methods]]
name = "status"
transport = "rest"
method = "syncing"

    [methods.response]
    status = 200
    field = "syncing" 
    format = "json"
