[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "kava"
node_type = "validator"
babel_version = "0.0.1"
node_version = "0.16.1" # recc mainnet
description = "kava blockchain validator"
api_host = "http://localhost:26656/"
# kava evm endopoint to connect to metamask: http://localhost:8545 

[monitor]
pid_file = "/var/run/kava.pid"

[[methods]]
name = "height"
transport = "rest"
method = "blocks/latest"

    [methods.response]
    status = 200
    field = "block.height"
    format = "json"

[[methods]]
name = "address"
transport = "rest"
method = "kava/hard/v1beta1/accounts"

    [methods.response]
    status = 200
    field = "accounts.base_account.pub_key.value"
    format = "json"

[[methods]]
name = "status"
transport = "rest"
method = "syncing"

    [methods.response]
    status = 200
    field = "syncing" 
    format = "json"
