[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "tezos"
node_type = "validator"
node_version = "14.0" # tezos version
min_babel_version = "0.0.1"
description = "tezos blockchain validator"
api_host = "http://localhost:8732/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    action = "allow"
    direction = "in"
    ports = [8732]

[requirements]
vcpu_count = 2
mem_size_mb = 8192
disk_size_gb = 100

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/tezos/data"


    [[supervisor.entry_point]]
    name = "tezos-node"
    body = """
    test -f /blockjoy/.init && \
    octez-node run --data-dir=/blockjoy/tezos/data --log-output=stdout
    """

[[methods]]
name = "height"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find

[[methods]]
name = "address"
transport = "jrpc"
method = "network/connections" 

    [methods.response]
    code = 200
    field = "peer_id" 

[[methods]]
name = "status"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find

[[methods]]
name = "init"
transport = "sh"
body = """
! test -f /blockjoy/.init && \
    octez-node config init --data-dir /blockjoy/tezos/data --network={{NETWORK}} --history-mode=babelref:'nets.{{NETWORK}}.history' && \
    octez-node config update --config-file=/blockjoy/tezos/data/config.json --data-dir=/blockjoy/tezos/data --rpc-addr="localhost:8732" && \
    touch /blockjoy/.init
"""

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "application_status"
transport = "sh"
body = """
echo -n "Cancelled"
"""

    [methods.response]
    status = 200
    format = "raw"

[nets.mainnet] 
net_type = "main"
url = ""
history = "rolling"

[nets.ghostnet]
net_type = "test"
url = ""
history = "rolling"

[nets.liamnet]
net_type = "test"
url = ""
history="rolling"

