[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "cardano"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.35.3"
description = "cardano blockchain validator"
api_host = "https://localhost:8090/"
ports = [8090]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "v2/blocks/latest/header"

    [methods.response]
    code = 200
    field = "block_height.quantity"

[[methods]]
name = "address"
transport = "jrpc"
method = "v2/wallets/{{WALLET_ID}}/keys" 

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "v2/network/information" 

    [methods.response]
    code = 200
    field = "sync_progress.status"
