[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "cardano"
node_type = "node"
node_version = "1.35.3"
min_babel_version = "0.0.1"
description = "cardano blockchain validator"
api_host = "http://localhost:8090/"
ports = [8090]

[requirements]
vcpu_count = 4
mem_size_mb = 16384
disk_size_gb = 100

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/cardano/data"

    [[supervisor.entry_point]]
    name = "cardano-node"
    body = """
    test -f /blockjoy/.init && \
    /blockjoy/cardano/cardano-node run \
    --config /blockjoy/cardano/configuration/cardano/{{NETWORK}}-config.json \
    --database-path /blockjoy/cardano/data/ \
    --socket-path /blockjoy/cardano/data/node.socket \
    --host-addr 0.0.0.0 \
    --port 1337 \
    --topology /blockjoy/cardano/configuration/cardano/{{NETWORK}}-topology.json
    """
    
    [[supervisor.entry_point]]
    name = "cardano-wallet"
    body = """
    /blockjoy/cardano-wallet/cardano-wallet-v2022-12-14-linux64/cardano-wallet serve --port 8090 \
    --node-socket /blockjoy/cardano/data/node.socket \
    --testnet /blockjoy/cardano/configuration/cardano/{{NETWORK}}-byron-genesis.json \
    --database /blockjoy/cardano-wallet/cardano-wallet-db \
    --token-metadata-server https://metadata.cardano-{{NETWORK}}.iohkdev.io
    """
    
    [[supervisor.entry_point]]
    name = "jupyter"
    body = """
    jt -t onedork && jupyter notebook --allow-root --ip 0.0.0.0
    """
    
[[methods]]
name = "height"
transport = "jrpc"
method = "v2/blocks/latest/header"

    [methods.response]
    code = 200
    field = "block_height.quantity"

[[methods]]
name = "address"
transport = "jrpc"
method = "v2/wallets/{{WALLET_ID}}/keys" 

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "v2/network/information" 

    [methods.response]
    code = 200
    field = "sync_progress.status"
    
[[methods]]
name = "init"
transport = "sh"
body = """
! test -f /blockjoy/.init && \
    rm -rf /blockjoy/cardano/data/* && pip3 install jupyterlab && pip3 install jupyter-server && pip3 install jupyterthemes && jt -t onedork
    touch /blockjoy/.init
"""

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "application_status"
transport = "sh"
body = """
echo -n "incomplete"
"""
    [methods.response]
    status = 200
    format = "raw"

[nets.testnet]
net_type = "test"
url = "https://cardano.org"

