[workspace]
members = [
    "babel_api",
    "babel",
    "bv",
    "bv_utils",
    "upload_manifest_generator",
]
resolver = "2"

[workspace.package]
version = "0.46.1"
edition = "2021"
rust-version = "1.66"
