application_name = "ethereum-geth"
node_type = "node"
version = "1.10.26-build.1"

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = ["software-properties-common"]
apt_source = ["universe"]
cmds = [
  "add-apt-repository -y ppa:ethereum/ethereum",
  "apt-get update",
  "apt-get install -y ethereum",
  "useradd -r -s /usr/sbin/nologin -d /nonexistent eth",
  "mkdir -p /blockjoy",
  "chown eth:eth /blockjoy",
  "wget -O lighthouse.tar.gz https://github.com/sigp/lighthouse/releases/download/v4.1.0/lighthouse-v4.1.0-x86_64-unknown-linux-gnu.tar.gz",
  "tar xvzf lighthouse.tar.gz --directory /usr/bin/",
  "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
  "yes | wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --disable-telemetry"
] 

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [
	        "cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/ethereum-geth/node/mnt/usr/bin/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/ethereum-geth/node/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/blockvisor/babel_api/protocols/ethereum-geth/node.toml {{.YafimHome}}/target/ethereum-geth/node/mnt/etc/babel.conf",
		"echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/ethereum-geth/node/mnt",
		"echo eth-rpc > {{.YafimHome}}/target/ethereum-geth/node/mnt/etc/hostname"
]
