nets = []

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "moonbeam"
node_type = "validator"
node_version = "0.28.0"
min_babel_version = "0.0.1"
description = "moonbeam blockchain validator"
api_host = "http://localhost:9933/"
ports = [9933]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 8
mem_size_mb = 16384
disk_size_gb = 1000 

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "chain_getFinalizedHead"

    [methods.response]
    code = 200
    field = "result" # find this

[[methods]]
name = "address"
transport = "jrpc"
method = "system_localPeerId" 

    [methods.response]
    code = 200
    field = "result" # find this

[[methods]]
name = "status"
transport = "jrpc"
method = "system_syncState"

    [methods.response]
    code = 200
    field = "result" # find this
