application_name = "polygon"
node_type = "node"
version = ""

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = []
apt_source = ["universe"]
cmds = [
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
  "cd ~/node/heimdall && sudo bash setup.sh",
  "cd ~/node/bor && sudo bash setup.sh",
  "sed -i -e '/seeds = \"\"/ s/= .*/= \"902484e868c6a4bace1bb3cf4b6ba1667561b158@18.228.218.160:26656,afc41bd37d549186cec915c5a4feb3071871cdc1@18.228.98.237:26656,587df41fb0198d72a9e153c608b2c0d840551429@35.182.147.162:26656,ad7bc1c45641454893c74b50357a1bd87778bb50@52.60.36.93:26656,1dcd26af9c43a9dd2035a856d37f27fd035622c8@13.51.221.221:26656,41f9896eb6a62ec68becbf1d4925ececdb726eb7@13.53.160.124:26656,e55dc772c8ce63035fd1fb0261da4c369fa9cf6c@52.65.134.57:26656,ef4d1d8e88e767239491a407035411f30d36f026@3.105.225.123:26656,03632361e5e076fef14989fc119faae7cce4ae60@3.36.134.67:26656\"/' -e '/persistent_peers = \"\"/ s/= .*/= \"902484e868c6a4bace1bb3cf4b6ba1667561b158@18.228.218.160:26656,afc41bd37d549186cec915c5a4feb3071871cdc1@18.228.98.237:26656,587df41fb0198d72a9e153c608b2c0d840551429@35.182.147.162:26656,ad7bc1c45641454893c74b50357a1bd87778bb50@52.60.36.93:26656,1dcd26af9c43a9dd2035a856d37f27fd035622c8@13.51.221.221:26656,41f9896eb6a62ec68becbf1d4925ececdb726eb7@13.53.160.124:26656,e55dc772c8ce63035fd1fb0261da4c369fa9cf6c@52.65.134.57:26656,ef4d1d8e88e767239491a407035411f30d36f026@3.105.225.123:26656,03632361e5e076fef14989fc119faae7cce4ae60@3.36.134.67:26656\"/' -e '/prometheus =/ s/= .*/= true/' -e '/max_open_connections =/ s/= .*/= 100/' ~/.heimdalld/config/config.toml",
  #"echo \"$(cat ~/node/bor/start.sh) \\ \" > ~/node/bor/start.sh",
  #"echo -e '  --bootnodes \"enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303,enode://3178257cd1e1ab8f95eeb7cc45e28b6047a0432b2f9412cff1db9bb31426eac30edeb81fedc30b7cd3059f0902b5350f75d1b376d2c632e1b375af0553813e6f@35.221.13.28:30303,enode://16d9a28eadbd247a09ff53b7b1f22231f6deaf10b86d4b23924023aea49bfdd51465b36d79d29be46a5497a96151a1a1ea448f8a8666266284e004306b2afb6e@35.199.4.13:30303,enode://ef271e1c28382daa6ac2d1006dd1924356cfd843dbe88a7397d53396e0741ca1a8da0a113913dee52d9071f0ad8d39e3ce87aa81ebc190776432ee7ddc9d9470@35.230.116.151:30303\"' >> ~/node/bor/start.sh",
#./heimdalld start --datadir /path/to/heimdall/data --config /path/to/heimdall/config.toml --log_level info
#./bor start --datadir /path/to/bor/data --config /path/to/bor/bor.toml --loglevel info

]

[build_machine]
apt_build_machine = []
git_repo = "git@github.com:blockjoy/blockvisor.git"
git_tag = "master"
build_cmds =  [
                "cp babelsup/usr/bin/babelsup target/polygon/node/mnt/usr/bin/",
                "cp babelsup/etc/systemd/system/babelsup.service target/polygon/node/mnt/etc/systemd/system/",
                "cp babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service target/polygon/node/mnt/etc/systemd/system/multi-user.target.wants/",
		"echo 'root:f&IS_rwh' | chpasswd -R /root/yafim/target/polygon/node/mnt/",
		"echo polygon > /root/yafim/target/polygon/node/mnt/etc/hostname",
		"sudo apt update",
		"sudo apt install -y build-essential git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python libssl-dev pkg-config clang llvm",
                "wget -O ./go-install.sh https://raw.githubusercontent.com/maticnetwork/node-ansible/master/go-install.sh",
                "bash ./go-install.sh",
                "sudo ln -nfs ~/.go/bin/go /usr/bin/go || exit 0",
		"git clone https://github.com/maticnetwork/heimdall",
		"git clone https://github.com/maticnetwork/bor",
		"git clone https://github.com/maticnetwork/launch",
                "cd heimdall && git checkout v0.3.0 && make install && cd -",
                "cd bor && git checkout v0.3.0 && make bor && cd -",
                "sudo cp ~/.go/bin/go /root/yafim/target/polygon/node/mnt/usr/bin/",
                "sudo cp -rf ~/go /root/yafim/target/polygon/node/mnt/root/",
                "sudo cp ~/go/bin/* /root/yafim/target/polygon/node/mnt/usr/bin/",
		"cd ~/yafim/bor/cmd/bootnode/ && go build -o ~/yafim/bor/cmd/bootnode/bootnode ~/yafim/bor/cmd/bootnode/main.go && sudo cp ~/yafim/bor/cmd/bootnode/bootnode /root/yafim/target/polygon/node/mnt/usr/bin/ ",
		"sudo mkdir -p /root/yafim/target/polygon/node/mnt/root/node /root/yafim/target/polygon/node/mnt/root/.bor/data/bor /root/yafim/target/polygon/node/mnt/usr/bin/root/.heimdall",
		"sudo bash ~/yafim/launch/mainnet-v1/service.sh",
		"sudo cp /root/yafim/*.service /root/yafim/target/polygon/node/mnt/etc/systemd/system/",
	        "sudo cp -rf /root/yafim/launch/mainnet-v1/sentry/sentry/* /root/yafim/target/polygon/node/mnt/root/node",
]
