application_name = "near"
node_type = "node"
version = "1.31.0"

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = []
apt_source = ["universe"]
cmds = [
  "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
]

[build_machine]
apt_build_machine = []
git_repo = "git@github.com:blockjoy/blockvisor.git"
git_tag = "master"
build_cmds =  [
                "cp babelsup/usr/bin/babelsup protocols/near/mnt/usr/bin/",
		"cp babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service protocols/near/mnt/etc/systemd/system/",
		"cp blockvisor/babel/protocols/near/near.toml protocols/near/mnt/etc/babel.conf",
		"echo 'root:f&IS_rwh' | chpasswd -R /root/yafim/protocols/near/mnt",
		"echo near > /root/yafim/protocols/near/mnt/etc/hostname",
		"sudo apt update",
		"sudo apt install -y git binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake gcc g++ python libssl-dev pkg-config clang llvm",
		"git clone https://github.com/near/nearcore.git",
		"rustup default stable-x86_64-unknown-linux-gnu",
		"cd nearcore && git checkout 1.31.0 && make neard",
		"mkdir -p /protocols/mnt/near/blockjoy/near",
		"cp nearcore/target/release/neard /protocols/mnt/near/blockjoy/near/"
]
