application_name = "polkadot"
node_type = "node"
version = ""

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = []
apt_source = []
cmds = [
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
  "apt update",
  "apt upgrade -y",
  "wget https://github.com/paritytech/polkadot/releases/download/v0.9.39/polkadot",
  "cp polkadot /usr/bin/",
  "polkadot --version",

]

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [
		"cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/polkadot/node/mnt/usr/bin/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/babelsup.service {{.YafimHome}}/target/polkadot/node/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/polkadot/node/mnt/etc/systemd/system/multi-user.target.wants/",
                "cp {{.YafimHome}}/blockvisor/babel_api/protocols/polkadot/node.toml {{.YafimHome}}/target/polkadot/node/mnt/etc/babel.conf",	
		"echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/polkadot/node/mnt/",
		"echo polkadot-node > {{.YafimHome}}/target/polkadot/node/mnt/etc/hostname",
]
