[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "tendermint"
node_type = "node"
node_version = "0.34.24"
min_babel_version = "0.0.1"
description = "tendermint blockchain validator"
api_host = "http://localhost:26657/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    action = "allow"
    direction = "in"
    ports = [26657]

[requirements]
vcpu_count = 2
mem_size_mb = 32768
disk_size_gb = 2000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/tendermint/"

    [[supervisor.entry_point]]
    name = "tendermint-node"
    body = """
    test -f /blockjoy/.init && \
    tendermint start --home babelref:'supervisor.data_directory_mount_point'  
    """

[[methods]]
name = "height"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.latest_block_height"

[[methods]]
name = "address"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "validator_info.pub_key.value" 

[[methods]]
name = "status"
transport = "jrpc"
method = "health"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "init"
transport = "sh"
body = """
! test -f /blockjoy/.init && \
tendermint init --home babelref:'supervisor.data_directory_mount_point' && \
touch /blockjoy/.init
"""

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "application_status"
transport = "sh"
body = """
echo -n "Cancelled"
"""

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "genesis_info"
transport = "jrpc"
method = "genesis"

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "https://rpc.cosmos.network:26657"

[nets.testnet]
net_type = "test"
url = "https://cosmos-testnet-rpc.allthatnode.com:26657"
