[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "aurora"
node_type = "validator"
node_version = "2.8.1"
min_babel_version = "0.0.1"
description = "aurora blockchain validator"
api_host = "http://localhost:8545/"
ports = [8545]

[requirements] 
vcpu_count = 8
mem_size_mb = 24576
disk_size_gb = 1000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "eth_syncing" # only if syncing

    [methods.response]
    code = 200
    field = "result.highestBlock"

[[methods]]
name = "address"
transport = "jrpc"
method = "eth_accounts"

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "eth_syncing"

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "https://mainnet.aurora.dev"

[nets.testnet]
net_type = "test"
url = "https://testnet.aurora.dev"