application_name = "cardano"
node_type = "node"
version = "1.35.5-build.1"

[image]
debian_version = "focal"
rootfs_size = "5G"
fs_type = "ext4"
apt_image = ["jq","python3-pip"]
apt_source = ["universe"]
cmds = [
  "wget -O cardano.tar.gz https://update-cardano-mainnet.iohk.io/cardano-node-releases/cardano-node-1.35.5-linux.tar.gz",
  "wget -O cardano-wallet.tar.gz https://github.com/input-output-hk/cardano-wallet/releases/download/v2022-12-14/cardano-wallet-v2022-12-14-linux64.tar.gz",
  "mkdir -p /blockjoy/cardano",
  "mkdir -p /blockjoy/cardano-wallet",
  "tar xvzf cardano.tar.gz --directory /blockjoy/cardano/",
  "tar xvzf cardano-wallet.tar.gz --directory /blockjoy/cardano-wallet/",
  "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
] 

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [
                "cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/cardano/node/mnt/usr/bin/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/babelsup.service {{.YafimHome}}/target/cardano/node/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/cardano/node/mnt/etc/systemd/system/multi-user.target.wants/",
		"cp {{.YafimHome}}/blockvisor/babel_api/protocols/cardano/cardano.toml {{.YafimHome}}/target/cardano/node/mnt/etc/babel.conf",
		"echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/cardano/node/mnt",
		"echo cardano > {{.YafimHome}}/target/cardano/node/mnt/etc/hostname"
]
