[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "harmony"
node_type = "validator"
node_version = "4.3.12"
min_babel_version = "0.0.1"
description = "harmony blockchain validator"
api_host = "http://localhost:9599" # shard 1 = 9598
# mainnet:  https://rpc.s0.t.hmny.io
ports = [9599, 9598]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "hmyv2_blockNumber"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "address"
transport = "jrpc"
method = "hmyv2_getNodeMetadata"

    [methods.response]
    code = 200
    field = "peerid"

[[methods]]
name = "status"
transport = "jrpc"
method = "hmyv2_getNodeMetadata"

    [methods.response]
    code = 200
    field = "consensus.mode"
