[env] # new
path_append = "/blockjoy/bin/"

[config]
protocol = "mina"
node_type = "validator"
node_version = "1.3.1.2"
min_babel_version = "0.0.1"
description = "mina blockchain validator"
api_host = "http://localhost:3087/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    policy = "allow"
    direction = "in"
    ports = [3087]

[requirements]
vcpu_count = 4 
mem_size_mb = 16384
disk_size_gb = 100

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = ""

[[methods]]
name = "address"
transport = "sh"
body = "mina advanced get-public-keys"

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "status"
transport = "sh"
body = "mina advanced node-status"

    [methods.response]
    status = 200
    format = "raw"

[nets.mainnet]
net_type = "main"
url = "https://storage.googleapis.com/mina-seed-lists/mainnet_seeds.txt"

[nets.testnet]
net_type = "test"
url = "https://storage.googleapis.com/seed-lists/devnet_seeds.txt"