[env] # new
path_append = "/blockjoy/bin/"

[config]
protocol = "arbitrum"
node_type = "validator"
node_version = "2.0.10"
min_babel_version = "0.0.1"
description = "arbitrum blockchain validator"
api_host = "http://localhost:8547/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    action = "allow"
    direction = "in"
    ports = [8547]

[requirements]
vcpu_count = 4 
mem_size_mb = 8192
disk_size_gb = 1000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "eth_syncing" # only if syncing

    [methods.response]
    code = 200
    field = "result.highestBlock"

[[methods]]
name = "address" # depreciated
transport = "jrpc"
method = "eth_accounts"

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "eth_syncing"

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "https://snapshot.arbitrum.io/mainnet/nitro.tar"

[nets.nitrogoerli]
net_type = "test"
url = "https://goerli-rollup.arbitrum.io/rpc" # tbd

