[env] # new
path_append = "/blockjoy/bin/"

[config]
protocol = "boba"
node_type = "validator"
node_version = "0.3.0"
min_babel_version = "0.0.1"
description = "boba blockchain validator"
api_host = "http://localhost:8545/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    action = "allow"
    direction = "in"
    ports = [8545]

[requirements]
vcpu_count = 4 
mem_size_mb = 16384
disk_size_gb = 100

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "eth_syncing" # only if syncing

    [methods.response]
    code = 200
    field = "result.highestBlock"

[[methods]]
name = "address" # depreciated
transport = "jrpc"
method = "eth_accounts"

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "rollup_getInfo"

    [methods.response]
    code = 200
    field = "result.syncing"

[nets.mainnet]
net_type = "main"
url = "https://mainnet.boba.network"

[nets.testnet]
net_type = "test"
url = "https://goerli.boba.network"