nets = {}

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "juno"
node_type = "validator"
node_version = "9.0.0"
min_babel_version = "0.0.1"
description = "juno blockchain validator"
api_host = "http://localhost:26657/"
ports = [26657]

[requirements]
vcpu_count = 8
mem_size_mb = 32768
disk_size_gb = 500

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.latest_block_height"

[[methods]]
name = "address"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "validator_info.pub_key.value" 

[[methods]]
name = "status"
transport = "jrpc"
method = "health"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "genesis_info"
transport = "jrpc"
method = "genesis"

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "https://raw.githubusercontent.com/CosmosContracts/mainnet/main/juno-1/genesis.json >~/.juno/config/genesis.json" # tbd

[nets.testnet]
net_type = "test"
url = "https://raw.githubusercontent.com/CosmosContracts/testnets/main/$CHAIN_ID" # tbd
