nets = {}

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "olabs"
node_type = "validator"
node_version = "1.0.0"
min_babel_version = "0.0.1"
description = "olabs blockchain validator"
api_host = "https://api.oasislabs.com/parcel/v1/" # rest api
ports = []

[requirements]
vcpu_count = 4
mem_size_mb = 8192
disk_size_gb = 400

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "rest"
method = "" # find 

    [methods.response]
    status = 200
    field = "" # find
    format = "raw" # find

[[methods]]
name = "address"
transport = "rest"
method = "identities/me" 

    [methods.response]
    status = 200
    field = "id"  
    format = "json"

[[methods]]
name = "status"
transport = "rest"
method = "" # find

    [methods.response]
    status = 200
    field = "" # find
    format = "raw" # find
