[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "olabs"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.0.0"
description = "olabs blockchain validator"
api_host = "https://api.oasislabs.com/parcel/v1/" # rest api

[monitor]
pid_file = "/var/run/olabs.pid"

[[methods]]
name = "height"
transport = "rest"
method = "" # find 

    [methods.response]
    status = 200
    field = "" # find
    format = "raw" # find

[[methods]]
name = "address"
transport = "rest"
method = "identities/me" 

    [methods.response]
    status = 200
    field = "id"  
    format = "json"

[[methods]]
name = "status"
transport = "rest"
method = "" # find

    [methods.response]
    status = 200
    field = "" # find
    format = "raw" # find
