[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "pokt"
node_type = "validator"
node_version = "0.8.3" #VERSION TBD
min_babel_version = "0.0.1"
description = "pokt blockchain validator"
api_host = "http://localhost:8081/v1/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    action = "allow"
    direction = "in"
    ports = [8081]

[requirements]
vcpu_count = 4
mem_size_mb = 16384
disk_size_gb = 500

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "rest"
method = "/query/height"

    [methods.response]
    status = 200
    field = ""
    format = "raw"

[[methods]]
name = "address"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "pubkey"

[[methods]]
name = "status"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "https://pokt-rpc.gateway.pokt.network"