[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "casper"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.4.6"
description = "casper blockchain validator"
api_host = "http://localhost:3000/" 

[monitor]
pid_file = "/var/run/casper.pid"

[[methods]]
name = "height"
transport = "jrpc"
method = "info_get_status"

    [methods.response]
    code = 200
    field = "result.value.last_added_block_info.height"

[[methods]]
name = "address"
transport = "jrpc"
method = "info_get_status" 

    [methods.response]
    code = 200
    field = "result.value.our_public_signing_key" 

[[methods]]
name = "status"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find
