nets = {}

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "casper"
node_type = "validator"
node_version = "1.4.6"
min_babel_version = "0.0.1"
description = "casper blockchain validator"
api_host = "http://localhost:3000/"
ports = [3000]

[requirements]
vcpu_count = 4
mem_size_mb = 32768
disk_size_gb = 2000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "info_get_status"

    [methods.response]
    code = 200
    field = "result.value.last_added_block_info.height"

[[methods]]
name = "address"
transport = "jrpc"
method = "info_get_status" 

    [methods.response]
    code = 200
    field = "result.value.our_public_signing_key" 

[[methods]]
name = "status"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find

[nets.mainnet]
net_type = "main"
url = "https://repo.casperlabs.io/casper-repo-pubkey.asc"

[nets.testnet]
net_type = "test"
url = "https://repo.casperlabs.io/casper-repo-pubkey.asc"