[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "casper"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.4.6"
description = "casper blockchain validator"
api_host = "http://localhost:3000/"
ports = [3000]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "info_get_status"

    [methods.response]
    code = 200
    field = "result.value.last_added_block_info.height"

[[methods]]
name = "address"
transport = "jrpc"
method = "info_get_status" 

    [methods.response]
    code = 200
    field = "result.value.our_public_signing_key" 

[[methods]]
name = "status"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find
