[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "pokt"
node_type = "validator"
babel_version = "0.0.1"
node_version = "0.8.3" #VERSION TBD
description = "pokt blockchain validator"
api_host = "http://localhost:8081/v1/"
data_directory_mount_point = "/blockjoy/miner/data"

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[monitor]
pid_file = "/var/run/pokt.pid"

[[methods]]
name = "height"
transport = "rest"
method = "/query/height"

    [methods.response]
    status = 200
    field = ""
    format = "raw"

[[methods]]
name = "address"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "pubkey"

[[methods]]
name = "status"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "result"
