[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "pokt"
node_type = "validator"
babel_version = "0.0.1"
node_version = "0.8.3" #VERSION TBD
description = "pokt blockchain validator"
api_host = "http://localhost:8081/v1/"
ports = [8081]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "rest"
method = "/query/height"

    [methods.response]
    status = 200
    field = ""
    format = "raw"

[[methods]]
name = "address"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "pubkey"

[[methods]]
name = "status"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "result"
