nets = {}

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "eos"
node_type = "validator"
node_version = "2.0.13"
min_babel_version = "0.0.1"
description = "eos blockchain validator"
api_host = "http://localhost:8080" # default
ports = [8080]

[requirements]
vcpu_count = 4
mem_size_mb = 16384
disk_size_gb = 200

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "vi/chain/get_info"

    [methods.response]
    code = 200
    field = "last_irreversible_block_num"

[[methods]]
name = "address"
transport = "jrpc"
method = "" # find 

    [methods.response]
    code = 200
    field = "" # find 

[[methods]]
name = "status"
transport = "jrpc"
method = "v1/net/connections"

    [methods.response]
    code = 200
    field = "syncing"

[nets.mainnet]
net_type = "main"
url = "mainnet.eosamsterdam.net" # tbd