application_name = "helium"
node_type = "validator"
version = "1.17.2-build.5"

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = ["jq","libsodium-dev","libdbus-1-dev"]
apt_source = ["universe"]
cmds = [
  "wget -O helium.tar.gz https://tools.stakejoy.com/helium-linux/miner-1.17.2.tar.gz",
  "mkdir -p /blockjoy/miner/data",
  "mkdir -p /opt/miner/update",
 "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",
  "tar xvzf helium.tar.gz --directory /blockjoy/miner/",
  "ln -s /blockjoy/miner/bin/miner /bin/miner", 
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf"
] 

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [
                "cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/helium/validator/mnt/usr/bin/",
                "cp {{.YafimHome}}/babelsup/etc/systemd/system/babelsup.service {{.YafimHome}}/target/helium/validator/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/helium/validator/mnt/etc/systemd/system/multi-user.target.wants/",
                "cp {{.YafimHome}}/blockvisor/babel_api/protocols/helium/validator.toml {{.YafimHome}}/target/helium/validator/mnt/etc/babel.conf",
                "echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/helium/validator/mnt",
                "echo helium > {{.YafimHome}}/target/helium/validator/mnt/etc/hostname"
]
