[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "sentinel"
node_type = "validator"
babel_version = "0.0.1"
node_version = "0.3.2"
description = "sentiel blockchain validator"
api_host = "http://localhost:26657/"
entry_point = "find"
data_directory_mount_point = "/blockjoy/miner/data"

[monitor]
pid_file = "/var/run/sentinel.pid"

[[methods]]
name = "height"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.latest_block_height"

[[methods]]
name = "address"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "validator_info.pub_key.value" 

[[methods]]
name = "status"
transport = "jrpc"
method = "health"

    [methods.response]
    code = 200
    field = "result"
