[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "helium"
node_type = "validator"
node_version = "1.15.9"
min_babel_version = "0.0.1"
description = "helium blockchain validator"
api_host = "http://localhost:4467/"
ports = [4467]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 10000
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "echo"
    args = ["Helium entry_point not configured!"]

[keys] # this is just an example
first = "/opt/secrets/first.key"
second = "/opt/secrets/second.key"
"*" = "/tmp"

# METHOD BLOCK-HEIGHT
# example:
# curl -X POST http://localhost:4467 \
#      -d '{"jsonrpc":"2.0","id":"id","method":"info_height"}' | jq .
# response:
# {
#   "id": "id",
#   "jsonrpc": "2.0",
#   "result": {
#     "epoch": 40440,
#     "height": 1492344
#   }
# }
[[methods]]
name = "height"
transport = "jrpc"
method = "info_height"

    [methods.response]
    code = 200
    field = "result.height"

# METHOD: P2P Address
# example:
# curl -X POST http://localhost:4467 \
#      -d '{"jsonrpc":"2.0","id":"id","method":"peer_addr"}' | jq .
# response:
# {
#   "id": "id",
#   "jsonrpc": "2.0",
#   "result": {
#     "peer_addr": "/p2p/11jD9oGmS8bqnMM6tDsxMoq9aAUrNjfSqjBDMtKAjXCYyvgbpLU"
#   }
# }
[[methods]]
name = "address"
transport = "jrpc"
method = "peer_addr"

    [methods.response]
    code = 200
    field = "result.peer_addr"

# METHOD name
# example:
# curl -X POST http://localhost:4467 \
#      -d '{"jsonrpc":"2.0","id":"id","method":"info_name"}' | jq .
# response:
# {
#   "id": "id",
#   "jsonrpc": "2.0",
#   "result": {
#     "name": "rare-jade-barbel"
#   }
# }
[[methods]]
name = "name"
transport = "jrpc"
method = "info_name"

    [methods.response]
    code = 200
    field = "result.name"

# METHOD: consensus status
# example:
# curl -X POST http://localhost:4467 \
#      -d '{"jsonrpc":"2.0","id":"id","method":"info_in_consensus"}' | jq .
# response:
# {
#   "id": "id",
#   "jsonrpc": "2.0",
#   "result": {
#     "in_consensus": false
#   }
# }
[[methods]]
name = "consensus"
transport = "jrpc"
method = "info_in_consensus"

    [methods.response]
    code = 200
    field = "result.in_consensus"

# METHOD: block age
# DESC: The age (in seconds) of the last block received.
# example:
# curl -X POST http://localhost:4467 \
#      -d '{"jsonrpc":"2.0","id":"id","method":"info_block_age"}' | jq .
# response:
# {
#   "id": "id",
#   "jsonrpc": "2.0",
#   "result": {
#     "block_age": 41
#   }
# }
[[methods]]
name = "block_age"
transport = "jrpc"
method = "info_block_age"

    [methods.response]
    code = 200
    field = "result.block_age"


# METHOD: summary
# DESC: The age of the last block received.
# example:
# curl -X POST http://localhost:4467 \
#      -d '{"jsonrpc":"2.0","id":"id","method":"info_summary"}' | jq .
# response:
# {
#   "id": "id",
#   "jsonrpc": "2.0",
#   "result": {
#     "block_age": 77,
#     "epoch": 40441,
#     "firmware_version": "cat: /etc/lsb_release: No such file or directory\n",
#     "gateway_details": "undefined",
#     "height": 1492366,
#     "mac_addresses": [
#       {
#         "bge3": "1402EC400C07"
#       },
#       {
#         "bge2": "1402EC400C06"
#       },
#       {
#         "bge1": "1402EC400C05"
#       },
#       {
#         "bge0": "1402EC400C04"
#       },
#       {
#         "bxe1": "A0D3C1F6F924"
#       },
#       {
#         "bxe0": "A0D3C1F6F920"
#       }
#     ],
#     "name": "rare-jade-barbel",
#     "peer_book_entry_count": 30829,
#     "sync_height": 1492366,
#     "uptime": 367135,
#     "version": "1.14.0"
#   }
# }
[[methods]]
name = "info"
transport = "jrpc"
method = "info_summary"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "genesis"
transport = "sh"
body = "/usr/bin/curl -s {{GENESIS_BLOCK_URL}} -o /h && /usr/local/bin/miner genesis load /h"

    [methods.response]
    # something?
    status = 0
    format = "raw"

[[methods]]
name = "version"
transport = "sh"
body = "miner versions | tail -n +2 | awk '{print $2}'"

    [methods.response]
    # something?
    status = 0
    format = "raw"

[[methods]]
name = "generate_keys"
transport = "sh"
body = "mkdir -p /opt/secrets && echo first > /opt/secrets/first.key && echo second > /opt/secrets/second.key"

    [methods.response]
    status = 0
    format = "raw"

[[methods]]
name = "init"
transport = "sh"
body = "echo 'noop for helium'"

    [methods.response]
    status = 200
    format = "raw"
