[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "band"
node_type = "validator"
node_version = "2.4.1"
min_babel_version = "0.0.1"
description = "band blockchain validator"
api_host = "http://localhost:26657/"

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    policy = "allow"
    direction = "in"
    ports = [26657]

[requirements]
vcpu_count = 2 
mem_size_mb = 8192
disk_size_gb = 100

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.latest_block_height"

[[methods]]
name = "address"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "validator_info.pub_key.value" 

[[methods]]
name = "status"
transport = "jrpc"
method = "health"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "genesis_info"
transport = "jrpc"
method = "genesis"

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "http://rpc.laozi1.bandchain.org"

[nets.testnet]
net_type = "test"
url = "https://rpc.laozi-testnet6.bandchain.org"