nets = []

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "cronos"
node_type = "validator"
node_version = "0.8.0"
min_babel_version = "0.0.1"
description = "cronos blockchain validator"
api_host = "http://localhost:8545/"
ports = [8545]

[requirements]
vcpu_count = 4
mem_size_mb = 4096
disk_size_gb = 1500

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "eth_syncing" # only if syncing

    [methods.response]
    code = 200
    field = "result.highestBlock"

[[methods]]
name = "address"
transport = "jrpc"
method = "eth_accounts"

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "eth_syncing"

    [methods.response]
    code = 200
    field = "result"
