[package]
name = "blockvisord"
publish = false
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "blockvisord"
path = "src/lib.rs"

[[bin]]
name = "bv"
path = "src/bin/bv.rs"

[[bin]]
name = "blockvisord"
path = "src/bin/blockvisord.rs"

[[bin]]
name = "installer"
path = "src/bin/installer.rs"

[dependencies]
anyhow = "1.0.56"
babel_api = {version = "*", path = "../babel_api"}
base64 = "0.13.0"
clap = {version = "3.1.15", features = ["derive", "cargo"]}
cli-table = "0.4"
firec = {git = "https://github.com/blockjoy/firec.git", rev = "88c3dec"}
futures-util = "0.3"
lazy_static = "1.4.0"
local-ip-address = "0.4.4"
petname = {version = "1.1.2", features = ["default_dictionary", "std_rng"], default-features = false}
prost = "0.10"
prost-types = "0.10"
serde = {version = "1.0.136", features = ["rc"]}
serde_json = "1.0.79"
sysinfo = "0.26.8"
systemstat = "0.2.2"
tokio = {version = "1.17.0", features = ["full"]}
tokio-stream = {version = "0.1.9", features = ["sync"]}
toml = "0.5.8"
tonic = {version = "0.7.2", features = ["tls-roots"]}
hyper = "0.14.14"
http = "0.2"
tracing = "0.1.34"
tracing-subscriber = {version = "0.3.11", features = ["env-filter", "fmt", "std"], default-features = false}
tracing-journald = "0.3.0"
uuid = {version = "1.0.0", features = ["serde", "v4"]}
fs_extra = "1.2.0"
tower = "0.4.13"
reqwest = {version = "0.11.11", features = ["rustls"]}
crc ="3.0.0"
async-trait = "0.1.60"
semver = "1.0.16"

[build-dependencies]
tonic-build = {version = "0.7.2", features = ["prost"]}

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
mockall = "0.11.3"
httpmock = "0.6"
jsonwebtoken = "7.2.0"
predicates = "2.1.1"
serial_test = "0.9.0"
tokio-stream = {version = "0.1.9", features = ["net"]}
