[package]
name = "blockvisord"
publish = false
edition.workspace = true
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "blockvisord"
path = "src/lib.rs"

[[bin]]
name = "bv"
path = "src/bin/bv.rs"

[[bin]]
name = "blockvisord"
path = "src/bin/blockvisord.rs"

[[bin]]
name = "installer"
path = "src/bin/installer.rs"

[[bin]]
name = "bvup"
path = "src/bin/bvup.rs"

[[bin]]
name = "blockvisord-dev"
path = "src/bin/blockvisord-dev.rs"

[dependencies]
bv_utils = {version = "*", path = "../bv_utils"}
anyhow = "1.0.68"
async-trait = "0.1.60"
babel_api = {version = "*", path = "../babel_api"}
base64 = "0.21.0"
cidr-utils = "0.5.10"
clap = {version = "4.2.4", features = ["derive", "cargo"]}
cli-table = "0.4"
crc = "3.0.0"
chrono = {version = "0.4.24", features = ["serde"]}
firec = {git = "https://github.com/blockjoy/firec.git", rev = "9e488cd"}
fs_extra = "1.2.0"
futures-util = "0.3"
lazy_static = "1.4.0"
local-ip-address = "0.5.1"
metrics = "0.20"
metrics-exporter-prometheus = "0.11.0"
petname = {version = "1.1.3", features = ["default_dictionary", "std_rng"], default-features = false}
prost = "0.11.6"
prost-types = "0.11.6"
rand = "0.8.5"
reqwest = {version = "0.11.14", features = ["rustls-tls"], default-features = false}
rumqttc = "0.20.0"
aws-sdk-s3 = "0.28.0"
semver = "1.0.16"
serde = "1.0.152"
serde_json = "1.0.91"
sysinfo = "0.29.2"
systemstat = "0.2.2"
tera = {version = "1.18.1", default-features = false}
thiserror = "1.0.31"
tokio = {version = "1.17.0", features = ["full"]}
tokio-stream = {version = "0.1.9", features = ["sync"]}
tonic = {version = "0.8.3", features = ["tls-roots"]}
tonic-rpc = { version = "0.2.0", features = ["bincode"] }
tower = "0.4.13"
tracing = "0.1.37"
uuid = {version = "1.2.2", features = ["serde", "v4"]}

[build-dependencies]
tonic-build = {version = "=0.8.2", features = ["prost"]}

[dev-dependencies]
assert_cmd = "2"
assert_fs = "1"
httpmock = "0.6.7"
jsonwebtoken = "8.2.0"
mockall = "0.11.3"
predicates = "2.1.5"
serial_test = "1"
tokio-stream = {version = "0.1.9", features = ["net"]}
http = "0.2"
hyper = "0.14.23"
