application_name = "klaytn"
node_type = "node"
version = "1.10.2-build.1"

[image]
debian_version = "focal"
rootfs_size = "20G"
fs_type = "ext4"
apt_image = ["ufw","jq"]
apt_source = []
cmds = [
  # Install Netdata
  "wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --disable-telemetry --non-interactive --dont-start-it --disable-cloud --static-only",

  # Create babelsup service
  "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",

  # Nameserver config
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",

  # Terminal config
  '''
  cat >> ~/.bashrc << EOF
stty cols 150
stty rows 40
export PS1="\[\e[32m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[36m\]\w\[\e[m\]\[\e[32m\]]\[\e[m\]\[\e[32;47m\]\\$\[\e[m\] "
export TERM=xterm-256color
EOF''',
]

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [
  # Netdata Streaming Configuration
  "mkdir -p {{.YafimHome}}/target/klaytn/node/mnt/opt/netdata/etc/netdata/",
  "cp {{.YafimHome}}/blockvisor/babel_api/netdata/stream.conf {{.YafimHome}}/target/klaytn/node/mnt/opt/netdata/etc/netdata/",

  # Install and auto start Babelsup service
  "cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/klaytn/node/mnt/usr/bin/",
  "cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/klaytn/node/mnt/etc/systemd/system/",

  # Copy Babel conf
  "cp {{.YafimHome}}/blockvisor/babel_api/protocols/klaytn/node.rhai {{.YafimHome}}/target/klaytn/node/mnt/etc/babel.conf",

  # Change Root Password and Hostname
  "echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/klaytn/node/mnt",
  "echo klaytn > {{.YafimHome}}/target/klaytn/node/mnt/etc/hostname",

  # Apt Update
  "sudo apt update -y",

  # Create folder
  "mkdir -p {{.YafimHome}}/target/klaytn/node/mnt/blockjoy/klaytn",
]
