application_name = "solana"
node_type = "node"
version = "1.15.2-build.1"

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = []
apt_source = []
cmds = [
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
  "sudo apt update",
  "sudo apt upgrade -y",
  "sh -c \"$(curl -sSfL https://release.solana.com/v1.15.2/install)\"",
  "solana --version",

]

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [
		"cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/solana/node/mnt/usr/bin/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/babelsup.service {{.YafimHome}}/target/solana/node/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/solana/node/mnt/etc/systemd/system/multi-user.target.wants/",
                "cp {{.YafimHome}}/blockvisor/babel_api/protocols/solana/node.toml {{.YafimHome}}/target/solana/node/mnt/etc/babel.conf",	
		"echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/solana/node/mnt/",
		"echo solana-node > {{.YafimHome}}/target/solana/node/mnt/etc/hostname",
]
