urn  = "cardano:validator"

[env]
path_append = "/blockjoy/bin/"

[config]
babel_version = "0.0.1"
node_version = "1.35.3"
node_type = "validator"
description = "cardano blockchain validator"
api_host = "https://localhost:8090/"

[monitor]
pid_file = "/var/run/cardano.pid"
[[methods]]
name = "height"
transport = "jrpc"
method = "v2/blocks/latest/header"

    [methods.response]
    code = 200
    field = "block_height.quantity"

[[methods]]
name = "address"
transport = "jrpc"
method = "v2/wallets/{walletId}/keys" 

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "v2/network/information" 

    [methods.response]
    code = 200
    field = "sync_progress.status"