urn  = "pokt:validator"

[env]
path_append = "/blockjoy/bin/"

[config]
babel_version = "0.0.1"
node_version = "0.8.3" #VERSION TBD
node_type = "validator"
description = "pokt blockchain validator"
api_host = "http://localhost:8081/v1/"

[monitor]
pid_file = "/var/run/pokt.pid"

[[methods]]
name = "height"
transport = "rest"
method = "/query/height"

    [methods.response]
    status = 200
    field = ""
    format = "raw"

[[methods]]
name = "address"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "pubkey"

[[methods]]
name = "status"
transport = "jrpc"
method = "" #find this

    [methods.response]
    code = 200
    field = "result"
