[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "tezos"
node_type = "validator"
babel_version = "0.0.1"
node_version = "14.0" # tezos version
description = "tezos blockchain validator"
api_host = "http://localhost:8732/"
ports = [8732]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find

[[methods]]
name = "address"
transport = "jrpc"
method = "network/connections" 

    [methods.response]
    code = 200
    field = "peer_id" 

[[methods]]
name = "status"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find
