[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "tezos"
node_type = "validator"
babel_version = "0.0.1"
node_version = "14.0" # tezos version
description = "tezos blockchain validator"
api_host = "http://localhost:8732/"
entry_point = "find"
data_directory_mount_point = "/blockjoy/miner/data"

[monitor]
pid_file = "/var/run/tezos.pid"

[[methods]]
name = "height"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find

[[methods]]
name = "address"
transport = "jrpc"
method = "network/connections" 

    [methods.response]
    code = 200
    field = "peer_id" 

[[methods]]
name = "status"
transport = "jrpc"
method = "" # find

    [methods.response]
    code = 200
    field = "" # find
