urn  = "moonbeam:validator"

[env]
path_append = "/blockjoy/bin/"

[config]
babel_version = "0.0.1"
node_version = "1701"
node_type = "validator"
description = "moonbeam blockchain validator"
api_host = "http://localhost:9933/" 

[monitor]
pid_file = "/var/run/moonbeam.pid"

[[methods]]
name = "height"
transport = "jrpc"
method = "chain_getFinalizedHead"

    [methods.response]
    code = 200
    field = "result" # find this

[[methods]]
name = "address"
transport = "jrpc"
method = "system_localPeerId" 

    [methods.response]
    code = 200
    field = "result" # find this

[[methods]]
name = "status"
transport = "jrpc"
method = "system_syncState"

    [methods.response]
    code = 200
    field = "result" # find this
