[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "centrifuge"
node_type = "validator"
babel_version = "0.0.1"
node_version = "10.15.1"
description = "centrifuge blockchain validator"
api_host = "http://localhost:9933/" 
entry_point = "find"
data_directory_mount_point = "/blockjoy/miner/data"

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[monitor]
pid_file = "/var/run/centrifuge.pid"

[[methods]]
name = "height"
transport = "jrpc"
method = "chain_getFinalizedHead"

    [methods.response]
    code = 200
    field = "result" # find

[[methods]]
name = "address"
transport = "jrpc"
method = "system_localPeerId" 

    [methods.response]
    code = 200
    field = "result" # find

[[methods]]
name = "status"
transport = "jrpc"
method = "system_syncState"

    [methods.response]
    code = 200
    field = "result" # find