application_name = "celo"
node_type = "node"
version = "1.7.4-build.1"

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = ["ufw"]
apt_source = []
cmds = [
  "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
  "yes | wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --stable-channel --disable-telemetry",
]

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [
                "cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/celo/node/mnt/usr/bin/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/celo/node/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/blockvisor/babel_api/protocols/celo/babel.rhai {{.YafimHome}}/target/celo/node/mnt/etc/babel.conf",
		"echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/celo/node/mnt",
		"echo celo > {{.YafimHome}}/target/celo/node/mnt/etc/hostname",
		"sudo apt update",
		"git clone https://github.com/celo-org/celo-blockchain.git || true && cd {{.YafimHome}}/celo-blockchain && git checkout v1.7.4 && make geth",
		"mkdir -p {{.YafimHome}}/target/celo/node/mnt/blockjoy/celo",
		"cp {{.YafimHome}}/celo-blockchain/build/bin/geth {{.YafimHome}}/target/celo/node/mnt/usr/bin/celo"
]
