[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "near"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.28.0"
description = "near blockchain validator"
api_host = "http://localhost:3030" 
data_directory_mount_point = "/blockjoy/miner/data"

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[monitor]
pid_file = "/var/run/near.pid"

[[methods]]
name = "height"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.latest_block_height" 

[[methods]]
name = "address"
transport = "jrpc"
method = "query" 

    [methods.response]
    code = 200
    field = "result.keys.public_key"

[[methods]]
name = "status"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.syncing"
