nets = {}

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "near"
node_type = "validator"
node_version = "1.28.0"
min_babel_version = "0.0.1"
description = "near blockchain validator"
api_host = "http://localhost:3030"
ports = [3030]

[requirements]
vcpu_count = 8
mem_size_mb = 24576
disk_size_gb = 1000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.latest_block_height" 

[[methods]]
name = "address"
transport = "jrpc"
method = "query" 

    [methods.response]
    code = 200
    field = "result.keys.public_key"

[[methods]]
name = "status"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "sync_info.syncing"
