[package]
name = "babel_api"
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
cidr-utils = "0.5.10"
serde = {version = "1.0.152", features = ["derive"]}
serde_bytes = "0.11.8"
strum_macros = "0.24"
tonic-rpc = { version = "0.2.0", features = ["bincode"] }
tonic = "0.8.3"
anyhow = "1.0.69"

[dev-dependencies]
walkdir = "2"
tracing = "0.1.37"
toml = "0.5.11"
