[env] # new
path_append = "/blockjoy/bin/"

[config]
protocol = "aptos"
node_type = "validator"
node_version = "1.2.4"
min_babel_version = "0.0.1"
description = "aptos blockchain validator"
api_host = "http://localhost:8080"
ports = [8080]

[requirements]
vcpu_count = 8
mem_size_mb =  32768
disk_size_gb = 1000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/aptos/node"

    [[supervisor.entry_point]]
    name = "aptos-node"
    body = """
    test -f /blockjoy/.init && \
    /blockjoy/aptos/aptos-node -f /blockjoy/aptos/fullnode.yaml
    """

[[methods]]
name = "height"
transport = "rest"
method = "/v1"
    
    [methods.response]
    status = 200
    field = "block_height"
    format = "json"

[[methods]]
name = "address"
transport = "rest"
method = "fullnode.mainnet.aptoslabs.com/v1/transactions"

    [methods.response]
    status = 200
    field = "signature.public_key" 
    format = "json"

[[methods]]
name = "status"
transport = "rest"
method = "fullnode.mainnet.aptoslabs.com/v1/-/healthy"

    [methods.response]
    status = 200
    field = "message"
    format = "json"


[[methods]]
name = "init"
transport = "sh"
body = """
! test -f /blockjoy/.init && ! test -f /blockjoy/.initbusy && \
touch /blockjoy/.initbusy && export TERM=xterm && \
curl babelref:'nets.{{NETWORK}}.waypoint' > /blockjoy/aptos/waypoint.txt 2>&1 | logger -t babel.init && \
curl babelref:'nets.{{NETWORK}}.url' > /blockjoy/aptos/genesis.blob 2>&1 | logger && \
axel -o /blockjoy/aptos/node/aptos.tar.lz4 -n 10 http://swarm01.stakejoy.com/aptos.tar.lz4 2>&1 | logger -t babel.init && \
sync && sleep 10 && lz4 -d -c  /blockjoy/aptos/node/aptos.tar.lz4 | tar -x -C /blockjoy/aptos/node/ && \
touch /blockjoy/.init && \
rm /blockjoy/.initbusy
"""

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "application_status"
transport = "sh"
body = """
echo -n "incomplete"
"""
    [methods.response]
    status = 200
    format = "raw"

[nets.mainnet]
net_type = "main"
url = "https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/mainnet/genesis.blob"
waypoint = "https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/mainnet/waypoint.txt"
snapshot = "https://snapshots.polkachu.com/snapshots/aptos/aptos_89414826.tar.lz4"

[nets.testnet]
net_type = "test"
url = "https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/testnet/genesis.blob"

[nets.devnet]
net_type = "dev"
url = "https://raw.githubusercontent.com/aptos-labs/aptos-networks/main/devnet/genesis.blob"
