[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "algo"
node_type = "validator"
node_version = "3.14.2"
min_babel_version = "0.0.1"
description = "algo blockchain validator"
api_host = "https://localhost:4001"
ports = [4001]

[requirements]
vcpu_count = 4 
mem_size_mb = 8192
disk_size_gb = 100

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/algorand/data"

    [[supervisor.entry_point]]
    name = "algod"
    body = "/usr/bin/algod -d /blockjoy/algorand/data/ -g /var/lib/algorand/genesis/{{NETWORK}}/genesis.json -o"

[[methods]]
name = "height"
transport = "rest"
method = "" # find 

    [methods.response]
    status = 200
    field = "" # find
    format = "raw" # find

[[methods]]
name = "address"
transport = "rest"
method = "" # find 

    [methods.response]
    status = 200
    field = "" # find 
    format = "raw" # find

[[methods]]
name = "status"
transport = "rest"
method = "/v2/status" 

    [methods.response]
    status = 200
    field = "" # find with test
    format = "json"

[[methods]]
name = "genesis_info"
transport = "rest"
method = "/genesis" 

    [methods.response]
    status = 200
    field = "result" # find with test
    format = "json"
[[methods]]
name = "init"
transport = "sh"
body = """
! test -f /blockjoy/.init && \
  touch /blockjoy/.init
"""

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "application_status"
transport = "sh"
body = """
echo -n "incomplete"
"""
    [methods.response]
    status = 200
    format = "raw"


[nets.testnet]
net_type = "test"
url = "x"
