[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "algo"
node_type = "validator"
babel_version = "0.0.1"
node_version = "3.9.4"
description = "algo blockchain validator"
api_host = "https://localhost:8443/"
entry_point = "find"
data_directory_mount_point = "/blockjoy/miner/data"

[monitor]
pid_file = "/var/run/algo.pid"

[[methods]]
name = "height"
transport = "rest"
method = "" # find 

    [methods.response]
    status = 200
    field = "" # find
    format = "raw" # find

[[methods]]
name = "address"
transport = "rest"
method = "" # find 

    [methods.response]
    status = 200
    field = "" # find 
    format = "raw" # find

[[methods]]
name = "status"
transport = "rest"
method = "v2/status" 

    [methods.response]
    status = 200
    field = "" # find with test
    format = "json"

[[methods]]
name = "genesis_info"
transport = "rest"
method = "genesis" 

    [methods.response]
    status = 200
    field = "result" # find with test
    format = "json"