[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "elrond"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.3.44"
description = "elrond blockchain validator"
api_host = "https://api.elrond.com/"
entry_point = "find"
data_directory_mount_point = "/blockjoy/miner/data"

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[monitor]
pid_file = "/var/run/elrond.pid"

[[methods]]
name = "height"
transport = "rest"
method = "blocks/count"

    [methods.response]
    status = 200
    field = "result"
    format = "json"

[[methods]]
name = "address"
transport = "rest"
method = "usernames/{username}"

    [methods.response]
    status = 200
    field = "address"
    format = "json"

[[methods]]
name = "status"
transport = "rest"
method = "hello"

    [methods.response]
    status = 200
    field = "hello" 
    format = "json"