nets = []

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "bbc" # binance beacon chain
node_type = "validator"
node_version = "0.8.2"
min_babel_version = "0.0.1"
description = "bbc blockchain validator"
api_host = "http://localhost:27147/" 
ports = [27147]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 4
mem_size_mb = 8192
disk_size_gb = 500 

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "abci_info"

    [methods.response]
    code = 200
    field = "result.response.last_block_height"

[[methods]]
name = "address"
transport = "jrpc"
method = "status"

    [methods.response]
    code = 200
    field = "validator_info.address" 

[[methods]]
name = "status"
transport = "jrpc"
method = "health"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "genesis_info"
transport = "jrpc"
method = "genesis"

    [methods.response]
    code = 200
    field = "result"
