[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "bsc"
node_type = "validator"
babel_version = "0.0.1"
node_version = "1.1.17"
description = "bsc blockchain validator"
api_host = "http://localhost:8545/"
entry_point = "find"
data_directory_mount_point = "/blockjoy/miner/data"

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[monitor]
pid_file = "/var/run/bsc.pid"

[[methods]]
name = "height"
transport = "jrpc"
method = "eth_syncing" # only if syncing

    [methods.response]
    code = 200
    field = "result.highestBlock"

[[methods]]
name = "address"
transport = "jrpc"
method = "eth_accounts"

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "eth_syncing"

    [methods.response]
    code = 200
    field = "result"