[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "flow"
node_type = "validator"
babel_version = "0.0.1"
node_version = "0.27.4"
description = "flow blockchain validator"
api_host = "http://localhost:3569/"
ports = [3569]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 1
mem_size_mb = 8192
disk_size_gb = 10

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "sh"
body = "flow blocks get block_height"

    [methods.response]
    status = 200
    format = "raw"

[[methods]]
name = "address"
transport = "sh"
body = "" # find 

    [methods.response]
    status = 200
    format = "raw" # find 

[[methods]]
name = "status"
transport = "sh"
body = "" # find

    [methods.response]
    status = 200
    format = "raw" # find
