[database]
connect_timeout_seconds = 30
database_url = "postgresql://postgres:postgres@localhost/blockvisor_dev"
idle_timeout_seconds = 900
max_connections = 128
max_lifetime_seconds = 3600
min_connections = 8

[http]
listen_address = "0.0.0.0"
listen_port = 8080

[telemetry]
log_format = "full"
opentelemetry = false
