[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "fuse"
node_type = "validator"
node_version = "2.0.1"
min_babel_version = "0.0.1"
description = "fuse blockchain validator"
api_host = "http://localhost:8545/"
ports = [8545]

[requirements] 
vcpu_count = 2
mem_size_mb = 8192
disk_size_gb = 30

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/miner/data"

    [[supervisor.entry_point]]
    name = "todo"
    body = ""

[[methods]]
name = "height"
transport = "jrpc"
method = "eth_syncing" # only if syncing

    [methods.response]
    code = 200
    field = "result.highestBlock"

[[methods]]
name = "address"
transport = "jrpc"
method = "eth_accounts"

    [methods.response]
    code = 200
    field = "result" 

[[methods]]
name = "status"
transport = "jrpc"
method = "eth_syncing"

    [methods.response]
    code = 200
    field = "result"

[nets.mainnet]
net_type = "main"
url = "https://rpc.fuse.io/"

[nets.testnet]
net_type = "test"
url = "https://rpc.fusespark.io/"