nets = []

[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "klaytn"
node_type = "validator"
node_version = "1.9.1"
min_babel_version = "0.0.1"
description = "klaytn blockchain validator"
api_host = "http://localhost:8551"
ports = [8551]
data_directory_mount_point = "/blockjoy/miner/data"

[requirements]
vcpu_count = 32 # CN is 72
mem_size_mb = 262144
disk_size_gb = 3000

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000

    [[supervisor.entry_point]]
    command = "todo"
    args = []

[[methods]]
name = "height"
transport = "jrpc"
method = "eth_blockNumber"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "address"
transport = "jrpc"
method = "eth_accounts"

    [methods.response]
    code = 200
    field = "result"

[[methods]]
name = "status"
transport = "jrpc"
method = "eth_syncing"

    [methods.response]
    code = 200
    field = "result"
