[env]
path_append = "/blockjoy/bin/"

[config]
protocol = "kava"
node_type = "validator"
node_version = "0.21.0" # recc mainnet
min_babel_version = "0.0.1"
description = "kava blockchain validator"
api_host = "http://localhost:26656/"
# kava evm endopoint to connect to metamask: http://localhost:8545

[firewall]
enabled = true
default_in = "deny"
default_out = "allow"

    [[firewall.rules]]
    name = "Allowed incoming traffic on port"
    policy = "allow"
    direction = "in"
    ports = [26656, 8545]

[requirements]
vcpu_count = 4
mem_size_mb = 32768
disk_size_gb = 500

[supervisor]
backoff_timeout_ms = 60000
backoff_base_ms = 100
log_buffer_capacity_ln = 1000
data_directory_mount_point = "/blockjoy/kava"

    [[supervisor.entry_point]]
    name = "kava-node"
    body = """
    test -f /blockjoy/.init && \
    kava --home babelref:'supervisor.data_directory_mount_point' start
    """

[[methods]]
name = "init"
transport = "sh"
body = """
! test -f /blockjoy/.init && \
kava --home babelref:'supervisor.data_directory_mount_point' init kava-node --chain-id kava_2222-10
touch /blockjoy/.init
"""

[[methods]]
name = "height"
transport = "rest"
method = "blocks/latest"

    [methods.response]
    status = 200
    field = "block.height"
    format = "json"

[[methods]]
name = "address"
transport = "rest"
method = "kava/hard/v1beta1/accounts"

    [methods.response]
    status = 200
    field = "accounts.base_account.pub_key.value"
    format = "json"

[[methods]]
name = "status"
transport = "rest"
method = "syncing"

    [methods.response]
    status = 200
    field = "syncing" 
    format = "json"

[nets.mainnet]
net_type = "main"
url = "https://evm.kava.io"

[nets.testnet]
net_type = "test"
url = "https://evm.testnet.kava.io"
