name: Blockvisor

on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "src/**.rs"
      - "tests/**.rs"
      - ".github/workflows/**"
  pull_request:
    branches:
      - "main"
      - "master"
    paths:
      - "src/**.rs"
      - "tests/**.rs"
      - ".github/workflows/**"

env:
  RUST_LOG: trace
  RUST_BACKTRACE: full

jobs:
  test:
    name: Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: >
          cargo build 
      - name: Reinstall
        run: >
          make reinstall
      # - name: Start test env
      #   run: >
      #     docker compose up -d
      - name: Test
        run: >
          cargo test
      # - name: Shutdown test env
      #   if: always()
      #   run: >
      #     docker compose down
  lints:
    name: Lints
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args:  -- --check
      - name: Catch common mistakes
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args:  -- -D warnings
