name: Deploy DO

on:
  push:
    branches:
      - "main"
      - "master"
    paths:
      - "api/**.rs"
      - ".github/workflows/**"
jobs:

  build:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Build container image
        run: docker build -t registry.digitalocean.com/stakejoy/blockvisor-api:latest .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/stakejoy/blockvisor-api:latest

      # - name: Deploy
      #   run: doctl apps create-deployment ${{ secrets.APP_ID_PROD }} --wait
