name: PR style

on:
  pull_request:
    branches: [master, main]
    types: [opened, edited, synchronize]

jobs:
  test:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Run check
        uses: transferwise/actions-pr-checker@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUCCESS_APPROVES_PR: false
          PR_CONTAINS_PATTERN: '.{5,}'
          SUCCESS_EMOJI: ''
          PR_COMMENT: |
            Please check description. 
            Should be meaningful and > 5 chars.
