name: Publish bundle

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'

permissions:
  contents: read

jobs:
  dispatch-publish:
    name: Dispatch BV Publish Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BJ_PROTOCOLS_WORKFLOW_APP_ID }}
          private-key: ${{ secrets.BJ_PROTOCOLS_APP_PK }}
          owner: blockjoy

      - name: Get Tag Name
        id: get-tag
        run: echo "TAG_NAME=$(git describe --tags)" >> $GITHUB_OUTPUT

      - name: Dispatch BV Publish Workflow
        id: dispatch-publish
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          DEFAULT_BRANCH=$(gh api repos/blockjoy/deployer --jq '.default_branch')

          gh workflow run bv-publish.yml \
            --repo blockjoy/deployer \
            --ref $DEFAULT_BRANCH \
            -f tag_name=${{ steps.get-tag.outputs.TAG_NAME }} \
            -f repository=blockjoy/blockvisor
