name: Publish bundle

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'

jobs:
  linux:
    name: Linux (musl)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Get Version
        run: echo GIT_VERSION=$(git describe --tags) >> $GITHUB_ENV
      - name: Install packages
        run: sudo apt install -y musl-tools jq
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
          unzip protoc-3.15.8-linux-x86_64.zip -d $HOME/.local
          export PATH="$PATH:$HOME/.local/bin"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          profile: minimal
          override: true
      - name: Build bundle file
        run: >
          make bundle
      - name: Build babelsup
        run: >
          make babelsup
      - name: Build upload_manifest_generator
        run: >
          make upload_manifest_generator
      - name: Upload to R2
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }} AWS_REGION=us-east-1 \
            aws --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/ s3 cp \
            /tmp/bundle.tar.gz \
            s3://bundle-dev/${{ env.GIT_VERSION }}/bvd-bundle.tgz
          AWS_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }} AWS_REGION=us-east-1 \
            aws --endpoint-url https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com/ s3 cp \
            /tmp/babelsup.tar.gz \
            s3://yafim/${{ env.GIT_VERSION }}/babelsup.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: |
            /tmp/bundle.tar.gz
            /tmp/babelsup.tar.gz
            /tmp/upload_manifest_generator
      - name: Publish bvup
        run: |
          echo "{\"tag_name\":\"${{ env.GIT_VERSION }}\",\"name\":\"${{ env.GIT_VERSION }}\",\"target_commitish\":\"main\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":false,\"body\":\"$(hexdump -ve '"\\" 1/1 "u%04x"' host_setup_guide.md)\"}" > /tmp/body.json
          RELEASE_ID=$(curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.BVUP_PUBLISH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28"  https://api.github.com/repos/blockjoy/bv-host-setup/releases --data "@/tmp/body.json" | jq .id) &&\
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.BVUP_PUBLISH_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -H "Content-Type: application/octet-stream" https://uploads.github.com/repos/blockjoy/bv-host-setup/releases/$RELEASE_ID/assets?name=bvup --data-binary "@/tmp/bvup"
