name: Publish bundle

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'

permissions:
  contents: write

jobs:
  publish:
    name: Publish BV Release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: x86_64-unknown-linux-musl
      - name: Get Version
        run: echo GIT_VERSION=$(git describe --tags) >> $GITHUB_ENV
      - name: Setup packages
        run: >
          sudo apt -y install build-essential pkg-config libssl-dev cmake musl-tools pigz awscli jq

      - name: Build bundle file
        run: >
          make bundle bundle-dev
      - name: Upload to B2
        run: |
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} AWS_REGION=us-east-1 \
            aws --endpoint-url ${{ secrets.AWS_ACCOUNT_URL }} s3 cp \
            /tmp/bundle.tar.gz \
            s3://bundle-dev/${{ env.GIT_VERSION }}/bvd-bundle.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          body_path: host_setup_guide.md
          files: |
            /tmp/bundle-dev.tar.gz
            /tmp/bundle.tar.gz
            /tmp/bvup
            /tmp/bundle/blockvisor/bin/nib
