name: Release BV

on:
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Bump Level (see https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md#bump-level)'
        required: true
        default: 'patch'
        type: choice
        options:
          - release
          - patch
          - minor
          - major
          - alpha
          - beta
          - rc

jobs:
  linux:
    name: BV release
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup environment
        run: |
          cargo install cargo-release
          git config user.email "engineering@blockjoy.com"
          git config user.name "CI"
      - name: Cargo Release
        run: >
          cargo release --execute --no-confirm ${{ inputs.bump_level }}
      - uses: ./.github/workflows/publish.yaml
