name: Release BV

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-**'

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: x86_64-unknown-linux-musl
      - name: Get Version
        run: echo GIT_VERSION=$(git describe --tags) >> $GITHUB_ENV
      - name: Setup packages
        run: >
          sudo apt -y install build-essential pkg-config libssl-dev cmake musl-tools pigz jq

      - name: Build bundle file
        run: >
          make bundle bundle-dev
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          body_path: host_setup_guide.md
          files: |
            /tmp/bundle-dev.tar.gz
            /tmp/bundle.tar.gz
            /tmp/bvup
            /tmp/bundle/blockvisor/bin/nib
