application_name = "algorand"
node_type = "node"
version = "3.14.2"

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = ["gnupg2"]
apt_source = ["universe"]
cmds = [
  "curl -o - https://releases.algorand.com/key.pub | sudo tee /etc/apt/trusted.gpg.d/algorand.asc",
  """add-apt-repository "deb [arch=amd64] https://releases.algorand.com/deb/ stable main" """,
  "apt-get update",
  "apt install -y algorand-devtools",
  "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
  "systemctl disable algorand.service"
] 

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [ 
		"cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/algorand/node/mnt/usr/bin/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/babelsup.service {{.YafimHome}}/target/algorand/node/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/multi-user.target.wants/babelsup.service {{.YafimHome}}/target/algorand/node/mnt/etc/systemd/system/multi-user.target.wants/",
		"cp {{.YafimHome}}/blockvisor/babel_api/protocols/algorand/node.toml {{.YafimHome}}/target/algorand/node/mnt/etc/babel.conf",
		"echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/algorand/node/mnt",
		"echo algorand > {{.YafimHome}}/target/algorand/node/mnt/etc/hostname"
]
