application_name = "algorand"
node_type = "node"
version = "3.16.3-build.7"

[image]
debian_version = "focal"
rootfs_size = "10G"
fs_type = "ext4"
apt_image = ["gnupg2","ufw", "jq"]
apt_source = ["universe"]
cmds = [
  "curl -o - https://releases.algorand.com/key.pub | sudo tee /etc/apt/trusted.gpg.d/algorand.asc",
  """add-apt-repository "deb [arch=amd64] https://releases.algorand.com/deb/ stable main" """,
  "apt-get update",
  "apt install -y algorand-devtools",
  "systemctl disable systemd-resolved.service",
  "rm /etc/dhcp/dhclient-enter-hooks.d/resolved",
  "rm /etc/resolv.conf",
  "echo 'nameserver 8.8.8.8' > /etc/resolv.conf",
  "echo 'nameserver 1.1.1.1' >> /etc/resolv.conf",
  "systemctl disable algorand.service",
  "ln -s /etc/systemd/system/babelsup.service /etc/systemd/system/multi-user.target.wants/babelsup.service",
  "wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh --disable-telemetry --non-interactive --disable-cloud --static-only",
  "echo 'TERM=xterm-256color' >> /root/.bashrc",
  "echo 'stty cols 200' >> /root/.bashrc",
  "echo 'stty rows 50' >> /root/.bashrc",
  "echo 'reset' >> /root/.bashrc"
] 

[build_machine]
apt_build_machine = []
git_repo = ""
git_tag = ""
build_cmds =  [ 
		"cp {{.YafimHome}}/babelsup/usr/bin/babelsup {{.YafimHome}}/target/algorand/node/mnt/usr/bin/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/babelsup.service {{.YafimHome}}/target/algorand/node/mnt/etc/systemd/system/",
		"cp {{.YafimHome}}/babelsup/etc/systemd/system/babelsup.service {{.YafimHome}}/target/algorand/node/mnt/etc/systemd/system/",
		"echo 'root:f&IS_rwh' | chpasswd -R {{.YafimHome}}/target/algorand/node/mnt",
		"echo algorand > {{.YafimHome}}/target/algorand/node/mnt/etc/hostname",
		"mkdir -p {{.YafimHome}}/target/algorand/node/mnt/opt/netdata/etc/netdata/",
		"cp {{.YafimHome}}/blockvisor/babel_api/netdata/stream.conf {{.YafimHome}}/target/algorand/node/mnt/opt/netdata/etc/netdata/"
]
